#Used by the Mongo implementation, currently the only one supported.
host: 127.0.0.1
port: 27017
database: core
username: test #OPTIONAL, comment out to disable this
password: test123 #OPTIONAL, comment out to disable this